### ISSUE TITLE
Add tag freezes session

### ISSUE THREAD

**Issue by techie2000** [mikenye/docker-picard#31]
and requires a restart of the container to get going again.

This only appears to occur when actioning a 'large' number of records in a Cluster (middle block of gui).
The cut-off point that moves the number of items from 'normal' to 'large' is currently unknown to me.
In the latest example that raised this issue I had 403 items.

How to recreate:

1. - Pull a large number of items from the left panel to the middle panel.
2. - Put them into a Cluster
3. - Right click on the bottom 'detail' section, and select Add Tag
4. - Choose musicbrainz_albumartistid
5. - Add the value of the tag

At this point the gui will freeze, and the container require a restart before further use can be be made of the app.

The container logs from just before and during the time of the event :
```
06/11/2020 15:22:58 active keyboard: turning X autorepeat off.

06/11/2020 15:22:58 created xdamage object: 0x200051
06/11/2020 15:27:57 idle keyboard: turning X autorepeat back on.

06/11/2020 15:38:22 client 2 network rate 1534.2 KB/sec (14680.1 eff KB/sec)
06/11/2020 15:38:22 client 2 latency: 0.8 ms
06/11/2020 15:38:22 dt1: 0.0155, dt2: 0.0254 dt3: 0.0008 bytes: 62167
06/11/2020 15:38:22 link_rate: LR_LAN - 1 ms, 1534 KB/s
06/11/2020 15:38:26 active keyboard: turning X autorepeat off.

E: 15:39:09,581 /usr/local/lib/python3.6/dist-packages/picard/webservice/__init__._handle_reply:445: Network request error for http://acousticbrainz.org:80/feec8b70-297a-4fb1-931b-6cdf52bd4047/low-level: Error transferring http://acousticbrainz.org:80/feec8b70-297a-4fb1-931b-6cdf52bd4047/low-level - server replied: NOT FOUND (QT code 203, HTTP code 404)


:09,581 /config/xdg/config/MusicBrainz/Picard/plugins/acousticbrainz_tonal-rhythm.zip/acousticbrainz_tonal-rhythm.process_data:72: AcousticBrainz Tonal-Rhythm: Network error retrieving acousticBrainz data for recordingId feec8b70-297a-4fb1-931b-6cdf52bd4047

E: 15:39:09,928 /usr/local/lib/python3.6/dist-packages/picard/webservice/__init__._handle_reply:445: Network request error for http://acousticbrainz.org:80/eb7b488a-fb8c-4707-8e25-8cc3a872caea/low-level: Error transferring http://acousticbrainz.org:80/eb7b488a-fb8c-4707-8e25-8cc3a872caea/low-level - server replied: NOT FOUND (QT code 203, HTTP code 404)


:09,928 /config/xdg/config/MusicBrainz/Picard/plugins/acousticbrainz_tonal-rhythm.zip/acousticbrainz_tonal-rhythm.process_data:72: AcousticBrainz Tonal-Rhythm: Network error retrieving acousticBrainz data for recordingId eb7b488a-fb8c-4707-8e25-8cc3a872caea

[1138:1186:1106/153916.407433:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory

[1138:1138:1106/153916.425943:ERROR:browser_dm_token_storage_linux.cc(94)] Error: /etc/machine-id contains 0 characters (32 were expected).

[1138:1199:1106/153916.493834:ERROR:bus.cc(393)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")

[1138:1199:1106/153916.493855:ERROR:bus.cc(393)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")

[1138:1199:1106/153916.493868:ERROR:bus.cc(393)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")

[1138:1199:1106/153916.493874:ERROR:bus.cc(393)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")

[1138:1245:1106/153916.537596:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory

[1138:1245:1106/153916.537615:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory

[1138:1245:1106/153916.537642:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory

[1138:1245:1106/153916.537656:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory

[1138:1245:1106/153916.537669:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory

[1196:1196:1106/153916.563061:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.

06/11/2020 15:44:48 idle keyboard: turning X autorepeat back on.
```

NOTE: I have just re-run the scenario described above to ensure i recorded the steps correctly and it has NOT occurred. Whether that means there is/was a memory related issue from previous activity done prior to the freeze which means it doesn't occur on a fresh system, it is difficult to say at this stage.

Note also, I have seen this occur on multiple occasions in the last few weeks, ie not just since the latest release.

**Comment by techie2000** [comment]
I'm getting similar errors much more repeatedly on the current release it seems - 3 times in last hour.
Latest occurrence was on 134 items in a Cluster, right clicking in the lower third detail section, option to Add New Tag appeared, but the session froze before I got to select it.

```
06/11/2020 19:30:57 Pixel format for client 127.0.0.1:
06/11/2020 19:30:57 32 bpp, depth 24, little endian
06/11/2020 19:30:57 true colour: max r 255 g 255 b 255, shift r 16 g 8 b 0
06/11/2020 19:30:57 no translation needed
06/11/2020 19:30:57 Enabling NewFBSize protocol extension for client 127.0.0.1
06/11/2020 19:30:57 Enabling full-color cursor updates for client 127.0.0.1
06/11/2020 19:30:57 Using image quality level 6 for client 127.0.0.1
06/11/2020 19:30:57 Using JPEG subsampling 0, Q79 for client 127.0.0.1
06/11/2020 19:30:57 Using compression level 9 for client 127.0.0.1
06/11/2020 19:30:57 Enabling LastRect protocol extension for client 127.0.0.1
06/11/2020 19:30:57 rfbProcessClientNormalMessage: ignoring unsupported encoding type Enc(0xFFFFFECC)
06/11/2020 19:30:57 Using tight encoding for client 127.0.0.1
06/11/2020 19:30:58 client_set_net: 127.0.0.1 0.0004
06/11/2020 19:30:58 created xdamage object: 0x40004f
06/11/2020 19:31:06 created selwin: 0x400050
06/11/2020 19:31:06 called initialize_xfixes()
06/11/2020 19:34:45 copy_tiles: allocating first_line at size 76
06/11/2020 19:34:46 client 1 network rate 1355.6 KB/sec (38256.2 eff KB/sec)
06/11/2020 19:34:46 client 1 latency: 6.0 ms
06/11/2020 19:34:46 dt1: 0.0018, dt2: 0.0079 dt3: 0.0060 bytes: 13213
06/11/2020 19:34:46 link_rate: LR_LAN - 5 ms, 1355 KB/s
[1096:1144:1106/193506.241985:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory

[1096:1096:1106/193506.249874:ERROR:browser_dm_token_storage_linux.cc(94)] Error: /etc/machine-id contains 0 characters (32 were expected).

[1096:1157:1106/193506.298204:ERROR:bus.cc(393)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")

[1096:1157:1106/193506.298230:ERROR:bus.cc(393)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")

[1096:1157:1106/193506.298247:ERROR:bus.cc(393)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")

[1096:1157:1106/193506.298263:ERROR:bus.cc(393)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")

[1096:1201:1106/193506.307869:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory

[1096:1201:1106/193506.307894:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory

[1096:1201:1106/193506.307935:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory

[1096:1201:1106/193506.307955:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory

[1096:1201:1106/193506.307972:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory

[1154:1154:1106/193506.394258:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.

06/11/2020 19:36:04 added missing keysym to X display: 093 0xc5 "Aring"
06/11/2020 19:41:05 idle keyboard: turning X autorepeat back on.
```

**Comment by mikenye** [comment]
I can reproduce the problem. No idea how to fix it at this stage, wondering whether the dbus errors above are related or a red herring. I'll probably look into this first.

**Comment by mikenye** [comment]
Adding "help wanted" tag to see if anyone else can shed some light on this.

**Comment by techie2000** [comment]
FYI, I've seen what looks to be the same issue in the last few days but with only a small number of items selected (<20) but with nothing at all generated in the log.

**Comment by mikenye** [comment]
Good to know. At least it’s likely not dbus then.

**Comment by techie2000** [comment]
Looks a safe assumption - two further experiences in last 2 days (latest with 474 items), neither which generated log entries.

**Comment by techie2000** [comment]
I found you can run with the `-d` option to but picard in to debug mode. I ran this from command line inside the container; I did some 'normal' activity and saw each action/reaction get logged. I then performed an action that was likely to induce failure (adding a tag to 500 items) and on observing the gui hang as predicted, went to the debug session...to find nothing logged :(

So this issue continues to be recreate-able, seemingly on-demand, but is not offering up any clues as to the source :(

**Comment by techie2000** [comment]
Thanks for the heads-up. I'll get chance at the weekend, hopefully...WFH is taking up a lot of my usually free time to crack on through my music collection these last few days :(

**Comment by phw** [comment]
Having the app freeze / become unresponsive on changes to the metadata box (add tag, toggle showing changed tags first) is a known bug, see https://tickets.metabrainz.org/browse/PICARD-2013 and related issues. Unfortunately we don't know what causes it, seems to be some issue with threads locking up. On some systems it is near impossible to replicate, while it happens frequently on other systems.

The dbus messages are likely a red herring. But thinking about it we probably need an option to completely disable the DBus integration for uses cases like this, does not make much sense inside the docker.

**Comment by mikenye** [comment]
Hi @phw, thanks for the information! I'll leave this issue open and check in on the Picard ticket from time to time.

I'd be very interested in being able to disable dbus, as running dbus inside a container is somewhat painful. :-)

**Comment by techie2000** [comment]
> Thanks for the heads-up. I'll get chance at the weekend, hopefully...WFH is taking up a lot of my usually free time to crack on through my music collection these last few days :(

Well, the wknd became today :) I have (re)tested this on the latest release and continue to experience the issue as described.

**Comment by phw** [comment]
> I have (re)tested this on the latest release and continue to experience the issue as described.

Yes, I can actually reproduce this in the dockerized version reliable. We have released Picard 2.5.3 today. I have some small hope that it might have some positive impact here as we refactored some of the event handling for changes on entities. Let's see if the lockup still happens in the docker version once it has been updated.

If it still happens maybe the docker version helps me in debugging this and getting to the root of it. I want to tackle this over the holidays.

**Comment by mikenye** [comment]
@phw & @techie2000: `docker.io/mikenye/picard:2.5.3` is now available for you to test with.

**Comment by phw** [comment]
Thanks. Issue still happens. I will debug this.

**Comment by mikenye** [comment]
Np. Let me know if I can help.

**Comment by mikenye** [comment]
@phw I can add you as a contributor so you can run a github action that builds & pushes the docker image if you need to build images for troubleshooting, just let me know.

**Comment by techie2000** [comment]
I'm away from home so don't have direct access to try this out, but FYI, accessing over ZeroTier One, as soon as I right-click in the lower third (to attempt to add a new tag), I'm getting a total app crash/restart (and no sign of the previously mentioned, but most likely red-herrings, 'errors' in the log). I noticed also that 2.5.5 has emerged since I last tried to do much with my tags!

**Comment by mikenye** [comment]
Yes, @phw has been hard at work. I note the upstream ticket is still marked as "unresolved" so it's unlikely to be fixed in the new version, but can't hurt to test it.

**Comment by phw** [comment]
Indeed that is not fixed yet. But good news is I could both reproduce the issue now with the Docker version and it allowed me to track down the root cause for the hanging and start working on a fix. It requires some more serious refactorings to the settings handling. My current goal would be to have a 2.6 release fixing this in early January.

**Comment by mikenye** [comment]
That's great troubleshooting @phw, top effort. Thanks for sticking with this!

**Comment by phw** [comment]
Fix for the freezing issue has been merged in https://github.com/metabrainz/picard/pull/1720

This freezing could potentially have happened in other situations (e.g. also when saving file and while saving toggling any option), but in practice most of the time happened with updates to the metadatabox.

**Comment by mikenye** [comment]
Hi @phw, I just had a look through your PR, wow. A lot of work went into that, well done.

I assume that the fix will make it into release 2.5.6?

**Comment by mikenye** [comment]
Fixed in release 2.5.6.

**Comment by techie2000** [comment]
Thank-you @phw thats a great fix and one which has removed by far my biggest annoyance in cleaning up the mess of tags i've found myself with over years of ripping. 
@mikenye I've deployed 2.5.6 and whilst not testing with some of the really large batches that previous real-life use-cases required, I have seen no issues on batches of ~400 which would routinely cause issues previously.

**Comment by mikenye** [comment]
@techie2000 thanks for the update mate! I'm glad you're issue has been cleared up. Big thanks to @phw for his hard work.

**Comment by phw** [comment]
@techie2000 Thanks for confirming that this works for you now.

Unfortunately the actual underlying issue is not completely resolved as I had thought. Looks like the changes just shifted probability of this freeze happening under certain circumstances. In another environment I can still reproduce a similar issue, and users also have reported this. That's also why the planned 2.6 beta has not yet happened :( My current plan is to completely rewrite the config system, I hope I can start with this soon.

**Comment by phw** [comment]
Another update: As it turned out the previous changes did not really resolve the issue. The underlying root cause is indeed a deadlock between internal mutex of QSettings and Python's GIL (global interpreter lock). It has been reported upstream and will get fixed in one of the next PyQt releases. But we also try to get a workaround for this into the Picard code. Currently I think https://github.com/metabrainz/picard/pull/1747 provides a working workaround for this issue, but needs some more testing.

**Comment by mikenye** [comment]
Thanks for the update, and well done hunting the problem down.
